apiVersion: apps/v1
kind: Deployment
metadata:
  name: guilhermerodrigues-atividade-kubernetes-i
spec:
  selector:
    matchLabels:
      app: guilhermerodrigues-atividade-kubernetes-i
  template:
    metadata:
      labels:
        app: guilhermerodrigues-atividade-kubernetes-i
    spec:
      containers:
      - name: guilhermerodrigues-atividade-kubernetes-i
        image: guilhermerodriguess/atividade-kubernetes-i
        resources: {}
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: guilhermerodrigues-atividade-kubernetes-i
spec:
  selector:
    app: guilhermerodrigues-atividade-kubernetes-i
  ports:
  - port: 80
    targetPort: 80