apiVersion: apps/v1
kind: Deployment
metadata:
  name: guilherme-banco-mongodb
spec:
  selector:
    matchLabels:
      app: guilherme-banco-mongodb
  template:
    metadata:
      labels:
        app: guilherme-banco-mongodb
    spec:
      containers:
      - name: guilherme-banco-mongodb
        image: guilhermerodriguess/atividade-kubernetes-i
        resources: {}
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Persi
metadata:
  name: guilherme-banco-mongodb
spec:
  selector:
    app: guilherme-banco-mongodb
  ports:
  - port: 80
    targetPort: 80